### ISSUE TITLE
scripts documentation needs to be improved

### ISSUE THREAD

**Issue by AliciaMstt** [tono2204/Mezcal_Yeast_Populations#10]
Scripts in the second semester directory need a small intro (comments) explaining what the script does

**Comment by tono2204** [comment]
Hello Alicia,

Do you mean inside each script or do you mean in the README?

Thanks a lot
Toño

**Comment by AliciaMstt** [comment]
I mean inside the each of the scripts. In the other scripts (first semester) you do indicate what they do briefly. This is good practice.

**Comment by tono2204** [comment]
Perfect. I have corrected this issue.
