### ISSUE TITLE
I want to download fastq files (sequencing reads) with SRA toolkit fastq-dump but I want to know if the process concluded correctly.

### ISSUE THREAD

**Issue by tono2204** [tono2204/Mezcal_Yeast_Populations#5]
Hello everyone, 
 I am downloading some reads files (fastq) from NCBI SRA with the help of the SRA Toolkit command ```fastq-dump --split-files```. However, my PI has warned me that there are times in which the downloads are finished before they are completed. As far as I know, fastq-dump does not generate an error log for the user to know if there was a problem with the download process. 
I want to ask you if you know of a more efficient way to download the fastq files from SRA or if there is a tool to do so that generates an error log. 

The SRA accession numbers of the samples are:

- X20 SRR4350270	*
- LL2012_016 SRR1868669, SRR1868670	 * Truseq
- R23   SRR4453439 *
- MSH-604  SRR1868751, SRR1868750	* Truseq
- LL2011_012 SRR1868663 , SRR1868664 * Nextera
- LL2012_001 SRR1868639, SRR1868640	* Truseq

As a small additional issue, I was wondering if you know a way to find out what type of library was used in a sequencing process since the paper does not mention it.

**Comment by FernandaDiaz12** [comment]
Hi, I suggest we use this Bioconductor package to download the SRA's.
https://bioconductor.org/packages/release/bioc/html/SRAdb.html

**Comment by Rodolfo47** [comment]
may [this](https://www.biostars.org/p/147148/) can work

**Comment by necrosnake91** [comment]
Hi Toño, 

Don´t forget to run ```getSRAdbFile()``` before downloading the requested files.

**Comment by FernandaDiaz12** [comment]
Fist install using BiocManager
`BiocManager::install("SRAdb")`

Then download and uncompress the updated SQLite file. 
`getSRAdbFile()` 

Finally, download the SRA files:

```
con = dbConnect('SQLite',srafile)
getSRAfile(c("SRR4350270",  "SRR1868669", "SRR1868670", "SRR4453439"),con,fileType='sra')
```

To extract the SRA info use the getSRAinfo command:
`getSRAinfo (in_acc=c("SRR4350270",  "SRR1868669", "SRR1868670", "SRR4453439"), sra_con=sra_con, sraType='sra')`

#### :)

**Comment by tono2204** [comment]
Thanks for the vdb-validate commando. We did a test with the SRA Accession number SRR9157013 and it worked just fine.
```
[turban@compute-00-06 prueba]$ vdb-validate SRR9157013
2019-10-16T21:31:34 vdb-validate.2.9.6 info: Validating '/mnt/Cromosoma/lmorales/turban/ncbi/sra/SRR9157013.sra'...
2019-10-16T21:31:34 vdb-validate.2.9.6 info: Database 'SRR9157013.sra' metadata: md5 ok
2019-10-16T21:31:34 vdb-validate.2.9.6 info: Table 'SEQUENCE' metadata: md5 ok
2019-10-16T21:31:35 vdb-validate.2.9.6 info: Column 'ALTREAD': checksums ok
2019-10-16T21:31:36 vdb-validate.2.9.6 info: Column 'QUALITY': checksums ok
2019-10-16T21:31:37 vdb-validate.2.9.6 info: Column 'READ': checksums ok
2019-10-16T21:31:37 vdb-validate.2.9.6 info: Database '/mnt/Cromosoma/lmorales/turban/ncbi/sra/SRR9157013.sra' contains only unaligned reads
2019-10-16T21:31:37 vdb-validate.2.9.6 info: Database 'SRR9157013.sra' is consistent

```
Thanks a lot.

**Comment by tono2204** [comment]
> Hi, I suggest we use this Bioconductor package to download the SRA's. [SRAdb](https://bioconductor.org/packages/release/bioc/html/SRAdb.html)


> Fist install using BiocManager
> `BiocManager::install("SRAdb")`
> 
> Then download and uncompress the updated SQLite file.
> `getSRAdbFile()`
> 
> Finally, download the SRA files:
> 
> ```
> sra_con <- dbConnect('SQLite',srafile)
> getSRAfile ( c("SRR4350270",  "SRR1868669", "SRR1868670", "SRR4453439"), sra_con, fileType='sra')
> ```
> 
> To extract the SRA info use the getSRAinfo command:
> `getSRAinfo (in_acc=c("SRR4350270", "SRR1868669", "SRR1868670", "SRR4453439"), sra_con=sra_con, sraType='sra')`
> 
> #### :)

Thanks for the advice but the necessary database to run this library is too big for our laptop´s hard drives. I guess that this library could be used in a cluster. :)

**Comment by necrosnake91** [comment]
You can use this general code:

```
sratoolkit.2.4.2-mac64/bin/./prefetch SRA_number
vdb-validate SRA_number
fastq-dump --split-file --gzip SRA.sra
```
Perhaps, you can use a ```for loop``` to download several SRA numbers. One hint, try to use a high-speed internet connection.

**Comment by tono2204** [comment]
Cris told us about an ipyrad package [sratools](https://ipyrad.readthedocs.io/en/latest/API-analysis/cookbook-sratools.html). I will try it.

**Comment by tono2204** [comment]
> You can use this general code:
> 
> ```
> sratoolkit.2.4.2-mac64/bin/./prefetch SRA_number
> vdb-validate SRA_number
> fastq-dump --split-file --gzip SRA.sra
> ```
> 
> Perhaps, you can use a `for loop` to download several SRA numbers. One hint, try to use a high-speed internet connection.

Perfect, I´ll take your advice into accounto. Unfortunately, it is very difficult to have a high-speed internet connection
